apiVersion: v2
name: iot-helm
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"

home: https://tiacloudconsult.io/
icon: https://landscape.cncf.io/logos/stack-storm.svg
source:
- https://github.com/tiacloudconsult/iot-helm-chart
keywords:
- tiacloud
- iot
- devops
- SRE
- automation
maintainers:
- name: Sharhan Alhassan
  email: sharhan.alhassan@tiacloud.io
  url: https://github.com/tiacloudconsult/sharhanalhassan
details: This Helm chart is Tia's

dependencies:
- name: rabbitmq
  version: 11.13.0
  repository: https://charts.bitnami.com/bitnami
  condition: rabbitmq.enabled

- name: mongodb
  version: 13.10.2
  repository: https://charts.bitnami.com/bitnami
  condition: mongodb.enabled

- name: dashboard-service
  version: 0.1.0
  repository: https://tiacloudconsult.github.io/mecdev-helm-chart-repo/charts
  condition: dashboard-service.enabled

- name: api-service
  version: 0.1.0
  repository: https://tiacloudconsult.github.io/mecdev-helm-chart-repo/charts
  condition: api-service.enabled


- name: consumer-service
  version: 0.1.0
  repository: https://tiacloudconsult.github.io/mecdev-helm-chart-repo/charts
  condition: consumer-service.enabled




